### ISSUE TITLE
Color Output in the CLI

### ISSUE THREAD

**Issue by norbusonam** [Azure/template-analyzer#157]
The output can be hard to read at times. Especially now, with analyze-directory, it can be a lot to scroll through. Coloring the output might make this easier.

We will have to decide when coloring is appropriate (when a rule is broken? when there was an error? both?)

**Comment by VeraBE** [comment]
Maybe we could use TTK as a reference for this, they output with colors

**Comment by anaismiller** [comment]
No longer high priority
