### ISSUE TITLE
Abstract away the checking of rule results

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#161]
Instead of looking at evaluations and results in the CLI and in BuiltInRuleTests

**Comment by yane3628** [comment]
Can you elaborate on what this would look like?

**Comment by JohnathonMohr** [comment]
Currently, Analyzer.Core returns everything that was evaluated, and the CLI has to filter what to display on the console based on what passed/failed.  This isn't ideal for the rule testing project or for other projects using Analyzer.Core directly, where this logic has to be somewhat duplicated.

Ideally, Analyzer.Core would take an extra argument/flag where the caller can specify what should be returned (just failing, failing and passing, other options?, etc.).

**Comment by anaismiller** [comment]
No longer high priority, no longer as problematic
