### ISSUE TITLE
"The template function 'variables' is not expected at this location"

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#184]
`An exception occurred: Error while processing template. - The template resource 'dnsLabelPrefix' at line '11' and column '23' is not valid: The template function 'variables' is not expected at this location. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details. - The template function 'variables' is not expected at this location. Please see https://aka.ms/arm-template-expressions for usage details.`

https://github.com/Azure/azure-quickstart-templates/blob/6a0af97995850602ba1aef5a32896827b4265fe6/application-workloads/opendx/openedx-tutor-lilac-ubuntu/azuredeploy.json

**Comment by JohnathonMohr** [comment]
[Quickstart pipeline results](https://github.com/Azure/azure-quickstart-templates/tree/6a0af97995850602ba1aef5a32896827b4265fe6/application-workloads/opendx/openedx-tutor-lilac-ubuntu) shows this template deployed successfully, so the syntax is valid.

**Comment by JohnathonMohr** [comment]
The failing template appears to parse without issue in the latest build.  This may have been fixed when the ARM library was updated in commit https://github.com/Azure/template-analyzer/commit/653c445e215f796a7d64c3ec89e9f095034ed11f.  @VeraBE can you verify?

**Comment by VeraBE** [comment]
Yes, it seems to be parsed properly now
