### ISSUE TITLE
Make language update for differentiating between rule scope narrowing and rule requirements

### ISSUE THREAD

**Issue by yane3628** [Azure/template-analyzer#20]
The JSON rule language needs some modification (new properties added) to differentiate between Value Operators that violate a rule and Value Operators that simply narrow the scope of when a rule should be enforced.

For example, if a rule is written that enforces both minimum and maximum values being present on a parameter if one of them is specified (i.e. the parameter can specify both or neither), when the rule checks to see if one is present, it should not report a failing rule.

**Comment by j0tr** [comment]
Feb original LOE was 2, increased to 3.  Remaining March LOE: 1
