### ISSUE TITLE
False positives on Quickstart template "Application Gateway with internal API Management and Web App"

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#209]
https://github.com/Azure/azure-quickstart-templates/blob/d06b9d1a8f0697a8b00a5588170bf1fef93dc947/quickstarts/microsoft.web/private-webapp-with-app-gateway-and-apim/azuredeploy.json#L336

The tool flags instances of:

- Diagnostic logs in App Services should be enabled
- FTPS only should be required in your Web App
- Latest TLS version should be used in your Web App

The results seem to be false positives related to setting properties with an instrumentation key from KeyVault, and rules not checking for name=web

**Comment by yane3628** [comment]
Investigating deprecation of the policy this is based off.

**Comment by j0tr** [comment]
"[Diagnostic logs in App Services should be enabled](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_AuditLoggingMonitoring_Audit_v2_deprecated.json)" policy is deprecated and appears to be replaced by "[Resource logs in App Services should be enabled](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_ResourceLoggingMonitoring_Audit.json)"
"[FTPS should be required in your Web App](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_AuditFTPS_WebApp_Audit.json)" policy still valid.
"[Latest TLS version should be used in your Web App](https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_RequireLatestTls_WebApp_Audit.json)" policy still valid.

**Comment by JohnathonMohr** [comment]
The latest in the `development` branch does not repro these false positives.

As noted in the description, there are indeed several rules which should be checking for "name=web" in the "Microsoft.Web/sites/config" resource.  However, as long a config resource exists that satisfies the rule, other non-applicable resources that *don't* satisfy the rule are still not flagged.

The bug in the rules (not checking for "name=web") could lead to *over-reporting*, where additional line numbers in non-applicable resources are reported alongside lines where the fix *should* be applied, so the rules do still need to be fixed.
I've opened #251 to track this.
