### ISSUE TITLE
Resolve resource type should account for resources in deployment resource types

### ISSUE THREAD

**Issue by JohnathonMohr** [Azure/template-analyzer#218]
When evaluating a rule, resolve resource type should account for resources of that type being defined in a deployment-type resource (in-line nested template).

It may be more appropriate to instead evaluate the in-line template on its own instead of comingling its resources with those of the primary template.  At the moment, it's unclear to me which would be better.  One challenge with doing this could be identifying line numbers correctly, as the template JSON would not start at line 1, but would instead start wherever the deployment resource is defined in that file.  This might be accounted for by simply relying on the Newtonsoft library, but care would be needed in implementation. The template's identifier - typically the file name of the template - would also be identical to the main template, necessitating a redefinition of the identifier to account for this possibility.

Related: #115.

**Comment by VeraBE** [comment]
This was already addressed by the nested templates PR
