### ISSUE TITLE
Rule filtering should be done as early as possible

### ISSUE THREAD

**Issue by yane3628** [Azure/template-analyzer#224]
### Please describe the feature.

Currently, filtering of rules (applying filtering from the configuration file) is done per template in the CLI. This should be done earlier so this filtering is not repeated logic for each template.

Ideal flow
1. Configuration file is loaded
2. Rules are filtered
3. Rules are "replaced" and passed to be evaluated against templates

**Comment by anaismiller** [comment]
Yes, it is done at the directory level before analysis.

**Comment by JohnathonMohr** [comment]
No longer an issue.
