### ISSUE TITLE
[BUG] "Rules passed" always says 0

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#235]
### Describe the bug

When running the tool with any template, the "rules passed" message in the console always says 0

### Expected behavior

It should show #rules - #(rules with errors)

### Reproduction Steps

Run the tool with any template

**Comment by VeraBE** [comment]
@JohnathonMohr I think this might be related to your latest PR

**Comment by JohnathonMohr** [comment]
I don't think this is true.  It depends whether the template being analyzed has resources that the rules look at or not.

The following template in the Azure Quickstarts for example has 4 failures and 2 "rules passed":
https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.web/app-function/azuredeploy.json
