### ISSUE TITLE
[FEATURE REQ] Improve format of exception information printed in console output

### ISSUE THREAD

**Issue by VeraBE** [Azure/template-analyzer#241]
### Please describe the feature or suggestion.

Adding line breaks and indentations when printing exceptions would improve the readability

We could also add more colors, as suggested in #157

### Additional context

This was discussed in #240

**Comment by JohnathonMohr** [comment]
@VeraBE can you review #244 and comment on whether that satisfies this?

@anaismiller do you think your PR satisfies this?

**Comment by VeraBE** [comment]
@JohnathonMohr I don't think so, I added this issue because of a comment by Yanelis about how exception messages look now in the console output, and that was not changed in that PR
