### ISSUE TITLE
Equals operator should be case-insensitive for objects

### ISSUE THREAD

**Issue by yane3628** [Azure/template-analyzer#27]
Paths `some.path` and `some.Path` are treated as unequal regardless of values when calling the equals operators on objects. This comparison should be case-insensitive.

**Comment by VeraBE** [comment]
@yane3628 Can you confirm if we still want to add support for this?

**Comment by yane3628** [comment]
I believe ARM templates are case insensitive, so this feature should still be needed.

**Comment by JohnathonMohr** [comment]
Ultimately, in my opinion, I don't think the equals operator needs to support comparing objects, and in that scenario, there isn't a feature to add.

**Comment by yane3628** [comment]
I think the issue is the path defined in the the template can be some.Path but the path defined in the rule is defined as some.path and the rule will not evaluate correctly since the engine is using the built in json deep equals operator. This is regardless of the type of property. For example, if some.path should equal "someValue", but it's value is "someOtherValue"  then it should be a violation. I don't believe it would even get flagged because the paths would not match as "some.path" != "some.Path".

For this template sample:
`{
...
    "some": {
        "Path": "someOtherValue"
    }
...
}`

and this rule sample:
`
{
    "resourceType": "resourceType",
    "path": "some.path",
    "equals": "someValue"
}
`

**Comment by JohnathonMohr** [comment]
That's just general path selection within a template, and that is already case-insensitive.

I believe the original intent with this issue was to allow this kind of rule:
```js
{
...
    "resourceType": "resourceType",
    "path": "...some",
    "equals": {
        "path": "someOtherValue"
    }
...
}
```

In this case, the equals operator is enforcing an entire object.  This is not documented as being valid for a rule, and I don't think this functionality is necessary.

**Comment by yane3628** [comment]
Since we don't officially support equally of objects, we'll close this as not planned.
