### ISSUE TITLE
Add metadata to result to help identify exactly what part of the check was violated

### ISSUE THREAD

**Issue by yane3628** [Azure/template-analyzer#33]
- Add message for determining the error
- Report Line Number and other metadata to CLI results

In an AllOf expression, this will help identify which sub-expressions caused the AllOf to fail.

Related Issue: https://github.com/Azure/template-analyzer/issues/199

**Comment by anaismiller** [comment]
more of a rule authoring, debugging tool.
(not high-priority right now)

**Comment by yane3628** [comment]
Close as duplicate of https://github.com/Azure/template-analyzer/issues/199
