### ISSUE TITLE
[BUG] Incorrect help uri in SARIF log

### ISSUE THREAD

**Issue by charlesoxyer** [Azure/template-analyzer#332]
### Describe the bug

The help uri that is listed in SARIF logs is directing to the old markdown file 'built-in-bpa-rules.md' instead of the updated 'built-in-rules.md' file.

Example from logs:
https://github.com/Azure/template-analyzer/blob/main/docs/built-in-bpa-rules.md/#ta-000005-latest-tls-version-should-be-used-in-your-api-app

### Expected behavior

Help uri directs to the correct markdown file 'built-in-rules.md'

### Reproduction Steps

Attempt to visit the help uri that is listed in SARIF logs.

**Comment by VeraBE** [comment]
@charlesoxyer this is expected in old versions of the tool. It won't happen with the latest release
