### ISSUE TITLE
Does template-analyzer support Pulumi? One of our customer using Pulumi to manage infrastructure (IaC code) 

### ISSUE THREAD

**Issue by vinod-soni-microsoft** [Azure/template-analyzer#337]
### Please describe the feature or suggestion.

Does template-analyzer support Pulumi? One of our customer using Pulumi to manage infrastructure (IaC code)

**Comment by nonik0** [comment]
No sorry, template-analyzer currently supports only ARM templates (JSON) and Bicep templates at this time.
