### ISSUE TITLE
[BUG] Bicep CIDR function generate error

### ISSUE THREAD

**Issue by RS-MPersson** [Azure/template-analyzer#340]
### Describe the bug

When using CIDR function, https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-cidr, in Bicep template-analyzer gives an error.

Exception details:
Microsoft.Azure.Templates.Analyzer.Core.TemplateAnalyzerException: Error compiling Bicep template
 ---> System.Exception: Bicep issues found:
The name "cidrSubnet" does not exist in the current context.

### Expected behavior

Expected behaviour is that this function is accepted in the validation without error.

### Reproduction Steps

Example of code in Bicep

param addressPrefix string = '10.0.0.0/23'
var subnets = [for i in range(0, 2): cidrSubnet(addressPrefix, 24, i)]

### Environment

Template Analyzer 0.5.1
VS Code 1.80.2

**Comment by nonik0** [comment]
This is likely due to an older version of the Bicep.Core library template-analyzer is using. We will be targeting .NET7 in the next release so we will be able to use the latest Bicep.Core release as well which should ideally resolve this as well.

**Comment by nonik0** [comment]
I forgot to update this issue earlier, but the last release updated the Bicep dependency to the latest available. Could you see if this Bicep dependency update fixes your issue?

**Comment by RS-MPersson** [comment]
Looks like this is solved now. It doesn't show up as an error anymore. Only a warning is shown.
