### ISSUE TITLE
Overlap with ARM teams ARM-ttk project

### ISSUE THREAD

**Issue by kilasuit** [Azure/template-analyzer#35]
In case you weren't aware there is over lap with this project and ARM-ttk (template test kit) & I would recommend you check that project out https://github.com/Azure/arm-ttk

**Comment by yane3628** [comment]
@kilasuit Thanks for reaching out! We are aware of the TTK and working with @bmoore-msft.

**Comment by bmoore-msft** [comment]
Yep, we know we have some overlap (there are at least 4 projects like this going on) and we're working on a plan to unify as much as we can - key is to not disrupt any usage/workflows.
