### ISSUE TITLE
[BUG] Excepted Rule not Being Ignored

### ISSUE THREAD

**Issue by securityboxtc** [Azure/template-analyzer#351]
### Describe the bug

When running the tool, the rules excluded per the scanning config file are still being run by the tool against the specified .bicep file.

### Expected behavior

When referenced, the config file with the exclusion list should force the Template Analyzer to exclude the listed rules. For example, if we want to exclude Rule Number AZR-000125, Azure.KeyVault.PurgeProtect, we should be able to add the rule number or name in the "exclusions" list and not have that rule run against the .bicep file being scanned.

### Reproduction Steps

Whether run as a local installation or as a Conan package from our production pipeline, the config file with the exclusion list does not exclude the listed rules. For example, if we want to exclude Rule Number AZR-000125, Azure.KeyVault.PurgeProtect, whether we use the rule number, name, or both, the rules are still run against the .bicep file, as is seen in the output. Attached is our testing config file for reference.
[ta-config.json](https://github.com/Azure/template-analyzer/files/13305964/ta-config.json)

### Environment

- Ubuntu 20.04
- Template Analyzer Version 0.5.2
- Run both from the CLI in Ubunu's Visual Studio Code (x64 1.84.1) and Ubuntu's built-in Terminal

**Comment by nonik0** [comment]
@securityboxtc Thanks for describing your issue. Looking at your config fule, I want to point out that unfortunately the filters in the configuration only applies to the JSON based rules (start with TA-*) and not the PSRule based rules (AZR-*). Also, your config file itself is not valid JSON.

**Comment by securityboxtc** [comment]
Good morning, @nonik0.  Apologies for the late response; I was on extended leave.

Thanks for the response and clarifying those points, especially about the two types of rules, PS and JSON.

Since the tool stops running when a file has been judged as noncompliant with an individual rule, is there any way to have the tool generate a report of all rule violations? If not, is that option or the option to also exclude PS-based rules on the future roadmap for this tool?

Thank you!

**Comment by JohnathonMohr** [comment]
Hi @securityboxtc, can you clarify what you mean by this?
> ... the tool stops running when a file has been judged as noncompliant with an individual rule

The tool will report all rules that a template doesn't comply with, not just the first rule violation.
