### ISSUE TITLE
Template Processor Assumes Templates are Deployed at Subscription Scope

### ISSUE THREAD

**Issue by yane3628** [Azure/template-analyzer#38]
If the template being checked is meant to be deployed in an existing resource group (at the resource group scope), the parser throws an error and cannot parse the template.

Repro Steps:
Use a template that has the resourceGroup field present. https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/deployments

**Comment by VeraBE** [comment]
Fixed in #231
