### ISSUE TITLE
Equals Operator throws exception when evaluating path that does not exist

### ISSUE THREAD

**Issue by JohnathonMohr** [Azure/template-analyzer#46]
If a path specified in a rule is evaluated with the equals operator does not exist in the template being evaluated, the operator throws a null-reference exception.

Instead, the operator should evaluate to `false`, as a path that doesn't exist will never equal any specific value.

**Comment by randomnoise** [comment]
This issue looks similar to issue #99 and i think it's resolved with PR #100.

**Comment by JohnathonMohr** [comment]
Thanks for catching that!

**Comment by JohnathonMohr** [comment]
Duplicate (or original of) #99.
