### ISSUE TITLE
[Built-in Rule] Remote debugging should be turned off for Web Applications

### ISSUE THREAD

**Issue by JohnathonMohr** [Azure/template-analyzer#64]
Azure Policy link: https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/App%20Service/AppService_DisableRemoteDebugging_WebApp_Audit.json
``` javascript
{
  "name": "AppService_DisableRemoteDebugging_WebApp",
  "description": "Remote debugging should be turned off for Web Applications",
  "recommendation": "Remote debugging should be turned off",
  "helpUri": "https://github.com/Azure/template-analyzer/docs/built-in-bpa-rules.md/#remote-debugging-should-be-turned-off-for-web-applications",
  "evaluation": {
    "resourceType": "Microsoft.Web/sites",
    "where": {
      "path": "properties.kind",
      "regex": "^app"
    },
    "evaluate": {
      "anyOf": [
        {
          "resourceType": "Microsoft.Web/sites/config",
          "where": {
            "path": "name",
            "equals": "web"
          },
          "evaluate": {
            "path": "properties.remoteDebuggingEnabled",
            "notEquals": true
          }
        },
        {
          "path": "properties.siteConfig.remoteDebuggingEnabled",
          "notEquals": true
        }
      ]  
    }
  }
}
```

**Comment by yane3628** [comment]
This rule has to be changed to an exclusive or logic. Since notEquals returns true if it's not specified, if true is specified in one part and the property is not specified in another, the OR results to true.

**Comment by yane3628** [comment]
@JohnathonMohr and @VeraBE I rewriting these rules to be exclusive or would make the rules a little long/complicated. Thoughts on maybe introducing an xor operator or something else?

**Comment by JohnathonMohr** [comment]
@yane3628 why not change it to allOf?

**Comment by yane3628** [comment]
@JohnathonMohr Can you give an example? In this case, when sites config is specified in one place it's not expected to be specified in the other.
